<?php
/**
 * Страница "Форма добавления виджета".
 * 
 * Русская локализации.
 * 
 * Этот файл является частью модуля веб-приложения GearMagic.
 * 
 * @copyright Copyright (c) 2015 Веб-студия GearMagic
 * @license https://gearmagic.ru/license/
 */
?>
<article>
    <h1>Добавление виджета</h1>
    <p>Форму добавления виджета на рабочий стол можно вызвать из пункта меню <b>"Добавить виджет"</b> информационной панели.</p>
    <h2>Поля формы</h2>
    <ul class="g-help-list">
        <li><b>Столбец рабочего стола.</b> Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat, sed diam voluptua;</li>
        <li><b>Настроить после добавления.</b> Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat, sed diam voluptua.</li>
    </ul>
</article>